import type { Metadata } from "next";

// These styles apply to every route in the application
import "./globals.css";
import SideMenu from "@/components/SideMenu";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="ko">
      <body>
        <SideMenu>{children}</SideMenu>
      </body>
    </html>
  );
}
